apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zabbix-mariadb
  spec:
    ports:
      - name: zabbix-mariadb
        port: 3306
        protocol: TCP
    selector:
      name: zabbix-mariadb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: zabbix-mariadb
  spec:
    tags:
       - name: latest
         from:
           kind: DockerImage
           name: centos/mariadb55-centos7
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: zabbix-mariadb
  spec:
    replicas: 1
    selector:
      name: zabbix-mariadb
    template:
      metadata:
        labels:
          name: zabbix-mariadb
      spec:
        containers:
        - name: zabbix-mariadb
          image: centos/mariadb55-centos7
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: zabbix
            - name: MYSQL_PASSWORD
              value: zabbix
            - name: MYSQL_DATABASE
              value: zabbix
            - name: TERM
              value: xterm
